# Generated by Django 4.2.3 on 2023-07-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0002_user_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.BooleanField(default=False),
        ),
    ]
