# Generated by Django 4.2.3 on 2023-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0003_user_verification_code_user_verification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="None", max_length=50),
        ),
    ]
