# Generated by Django 4.2.3 on 2023-07-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0008_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
