# Generated by Django 4.2.3 on 2023-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0013_mediapost_caption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediapost",
            old_name="user",
            new_name="author",
        ),
    ]
