# Generated by Django 4.2.3 on 2023-07-26 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("facebook_app", "0017_mediacomment_textcomment_delete_postcomment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MediaComment",
            new_name="MediaPostComment",
        ),
        migrations.RenameModel(
            old_name="TextComment",
            new_name="TextPostComment",
        ),
    ]
