# Generated by Django 4.2.3 on 2023-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0018_rename_mediacomment_mediapostcomment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
