# Generated by Django 4.2.3 on 2023-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0019_alter_message_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textpost",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
