# Generated by Django 4.2.3 on 2023-07-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0020_alter_textpost_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediapost",
            name="time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="mediapostcomment",
            name="time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="textpostcomment",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
