# Generated by Django 4.2.3 on 2023-07-27 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "facebook_app",
            "0021_alter_mediapost_time_alter_mediapostcomment_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TextStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("time", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facebook_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        upload_to="media/posts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "mp4"]
                            )
                        ],
                    ),
                ),
                ("caption", models.TextField(default="")),
                ("time", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facebook_app.user",
                    ),
                ),
            ],
        ),
    ]
