# Generated by Django 4.2.3 on 2023-07-27 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_app", "0024_alter_friendrequests_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendrequests",
            unique_together={("user_email", "friend_email")},
        ),
    ]
